// Execute the actual Java-generated bootstrap script, with localStorage/navigation as boundaries.
const assert=require('assert/strict'),vm=require('vm'),cp=require('child_process');
let n=0;function check(name,f){f();n++;console.log('PASS '+name)}
function html(mode,url){return cp.execFileSync('java',['-cp',process.env.EXTENSIONS_CLASSES||'build/extensions-host/classes','com.prismml.bonsailocal.repair.BootstrapDump',String(mode),url||'http://127.0.0.1:41414/mcp/fixture'],{encoding:'utf8'})}
function boot(mode,initial={},url){const page=html(mode,url),script=page.match(/<script>([\s\S]*?)<\/script>/)[1],store={...initial};let nav=null,message={textContent:''};const context=vm.createContext({localStorage:{getItem:k=>store[k]??null,setItem:(k,v)=>store[k]=v},location:{replace:p=>nav=p},document:{getElementById:()=>message}});vm.runInContext(script,context);return {page,store,nav,message:message.textContent,cfg:store['LlamaUi.config']?JSON.parse(store['LlamaUi.config']):null};}
function own(b){return JSON.parse(b.cfg.mcpServers).find(s=>s.id==='bonsai-local-web')}
check('first bootstrap creates local MCP entry without API secrets',()=>{let b=boot(0);assert.equal(own(b).enabled,false);assert.equal(own(b).name,'bonsai-web');assert.equal(own(b).useProxy,false);assert.equal(b.nav,'/');assert(!b.page.includes('X-Subscription-Token'))});
check('Ask enables tools but does not grant Always permission',()=>{let b=boot(1);assert.equal(own(b).enabled,true);assert.deepEqual(JSON.parse(b.store['LlamaUi.alwaysAllowedTools']),[])});
check('Always grants only two correct MCP selection identities',()=>{let b=boot(2);assert.deepEqual(JSON.parse(b.store['LlamaUi.alwaysAllowedTools']),['mcp-bonsai-local-web:web_search','mcp-bonsai-local-web:web_fetch'])});
const saved={'LlamaUi.config':JSON.stringify({theme:'dark',systemMessage:'private system',mcpServers:JSON.stringify([{id:'other',enabled:true,url:'https://other.example/mcp',headers:'secret-unrelated-header'},{id:'bonsai-local-web',url:'old-port'}])}),'LlamaUi.alwaysAllowedTools':JSON.stringify(['browser:get_time','mcp-bonsai-local-web:web_fetch']),'unrelated':'keep'};
check('bootstrap preserves other settings/server credentials/permissions',()=>{let b=boot(1,saved);assert.equal(b.cfg.theme,'dark');assert.equal(b.cfg.systemMessage,'private system');assert.equal(JSON.parse(b.cfg.mcpServers)[0].headers,'secret-unrelated-header');assert.deepEqual(JSON.parse(b.store['LlamaUi.alwaysAllowedTools']),['browser:get_time']);assert.equal(b.store.unrelated,'keep');assert.equal(JSON.parse(b.cfg.mcpServers).length,2)});
check('Off revokes own remembered permission and leaves unrelated permission',()=>{let b=boot(0,saved);assert.equal(own(b).enabled,false);assert.deepEqual(JSON.parse(b.store['LlamaUi.alwaysAllowedTools']),['browser:get_time'])});
check('new process replaces own endpoint, does not accumulate duplicate MCP servers',()=>{let b=boot(2,saved);let c=boot(2,b.store,'http://127.0.0.1:55555/mcp/new-token');assert.equal(JSON.parse(c.cfg.mcpServers).length,2);assert(own(c).url.includes('55555'));assert.equal(JSON.parse(c.store['LlamaUi.alwaysAllowedTools']).length,3)});
check('invalid existing settings are not overwritten',()=>{const initial={'LlamaUi.config':'{broken','LlamaUi.alwaysAllowedTools':'[]'};let page=html(1),store={...initial},message={};vm.runInNewContext(page.match(/<script>([\s\S]*?)<\/script>/)[1],{localStorage:{getItem:k=>store[k]??null,setItem:(k,v)=>store[k]=v},location:{replace:()=>assert.fail('must not navigate')},document:{getElementById:()=>message}});assert.deepEqual(store,initial);assert(message.textContent.includes('не удалены'))});
check('invalid MCP list fails before storage mutation',()=>{let bad={...saved,'LlamaUi.config':JSON.stringify({mcpServers:'{"bad":1}',theme:'dark'})},b=boot(1,bad);assert.equal(b.nav,null);assert.deepEqual(b.store,bad)});
check('invalid permissions fail before any settings write',()=>{let bad={...saved,'LlamaUi.alwaysAllowedTools':'{}'},b=boot(1,bad);assert.equal(b.nav,null);assert.deepEqual(b.store,bad)});
check('bootstrap string cannot close script/inject markup',()=>{let b=boot(0,{},'http://example/</script><script>throw 99</script>');assert.equal((b.page.match(/<script>/g)||[]).length,1);assert.equal(own(b).url,'http://example/</script><script>throw 99</script>')});
console.log('BOOTSTRAP CHECKS '+n+'; real generated script, storage/navigation boundary doubles.');
