// Execute the shipped JavaScript. DOM and Android bridge are boundary doubles.
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const html=fs.readFileSync(__dirname+'/../app/assets/index.html','utf8');
const js=html.match(/<script>([\s\S]*?)<\/script>/)[1];
const models=[{index:0,quant:'PTQ1_0',name:'Ternary-Bonsai-2-27B-PTQ1_0.gguf',size:5946648928,ready:false},{index:1,quant:'PQ2_0',name:'Ternary-Bonsai-2-27B-PQ2_0.gguf',size:7206168928,ready:false}];
let s={engine:{state:0,exit:-999,total:0,done:0,error:''},transfer:{state:'idle',busy:false,done:0,total:7206168928,speed:0,connections:8,resumable:false,error:''},hasModel:false,options:{modelIndex:1,ctxSize:16384,kvQ4:false,threads:4,batchThreads:8,thinking:0},models,benchmark:{state:'idle',busy:false,response:'',error:'',settings:{},elapsedMs:0}},called=[],consent=false,lastConfirm='',configureError='';const elements={};
const bridge={status:()=>JSON.stringify(s),configure:(...args)=>{called.push(['configure',...args]);if(configureError)return configureError;let [modelIndex,ctxSize,kvQ4,threads,batchThreads,thinking]=args;s.options={modelIndex,ctxSize,kvQ4,threads,batchThreads,thinking};s.hasModel=models[modelIndex].ready;return '';},runtimeInfo:()=>'<runtime text>',start:()=>called.push('start'),stop:()=>called.push('stop'),selfTest:()=>called.push('selfTest'),download:()=>called.push('download'),chooseFile:()=>called.push('chooseFile'),pause:()=>called.push('pause'),benchmark:()=>called.push('benchmark')};
const context=vm.createContext({document:{getElementById(id){return elements[id]||={style:{},hidden:false,disabled:false,textContent:'',value:'',checked:false};}},Bonsai:bridge,confirm:text=>(lastConfirm=text,consent),setTimeout:()=>{},console});
vm.runInContext(js,context);let n=0;
function check(name,fn){fn();console.log('PASS '+name);n++;}function run(code){return vm.runInContext(code,context)}function poll(){run('poll()')}function resetCalls(){called=[]}
check('startup never downloads, loads model, or changes settings',()=>assert.equal(called.length,0));
check('saved model and CPU options populate controls',()=>{assert.equal(elements.model.value,'1');assert.equal(elements.ctx.value,'16384');assert.equal(elements.threads.value,'4');assert.equal(elements.batchThreads.value,'8');assert.equal(elements.thinking.value,'0');assert(!elements.kvq4.checked)});
check('picker available without model',()=>assert(!elements.pick.hidden&&!elements.pick.disabled));
check('chat/load/benchmark hidden or disabled without model',()=>assert(elements.chat.hidden&&elements.go.hidden&&elements.bench.disabled));
check('PQ2 name and additional copy size displayed',()=>{assert(elements.modelInfo.textContent.includes('PQ2_0'));assert(elements.importInfo.textContent.includes('7.21'))});
check('cancel download is no-op',()=>{run('confirmDownload()');assert.equal(called.length,0)});
check('download applies all six settings then starts transfer',()=>{consent=true;run('confirmDownload()');assert.deepEqual(called,[['configure',1,16384,false,4,8,0],'download'])});
check('PQ2 import copy consent not PTQ size',()=>{resetCalls();run('chooseLocal()');assert.equal(called.at(-1),'chooseFile');assert(lastConfirm.includes('PQ2_0')&&lastConfirm.includes('7.21'))});
check('failed native settings prevent any download',()=>{configureError='BUSY';resetCalls();run('confirmDownload()');assert(!called.includes('download'));assert.equal(elements.status.textContent,'BUSY');configureError=''});
check('changing format applies actual model index',()=>{resetCalls();elements.model.value='0';run('saveSettings(false)');assert.equal(called[0][1],0);poll();assert(elements.modelInfo.textContent.includes('PTQ1_0'))});
check('native settings error restores last saved controls',()=>{elements.model.value='1';configureError='blocked';run('saveSettings(false)');assert.equal(elements.model.value,'0');configureError=''});
check('Base preset preserves format and enables F16/off/4+8',()=>{elements.ctx.value='262144';elements.kvq4.checked=true;elements.threads.value='8';elements.thinking.value='2';run('preset()');assert.deepEqual(called.at(-1),['configure',0,16384,false,4,8,0])});
check('256K F16 warning names excessive KV memory',()=>{elements.ctx.value='262144';elements.kvq4.checked=false;run('memoryHint()');assert(elements.memory.textContent.includes('16.0'));assert(elements.memory.textContent.includes('22 ГиБ'))});
check('cancel large context launch does not launch model',()=>{consent=false;resetCalls();run('startModel()');assert.equal(called.length,0);consent=true;run('preset()')});
check('transfer displays measured download speed',()=>{s.transfer={...s.transfer,state:'download',busy:true,done:3603084464,total:7206168928,speed:12500000};poll();assert.equal(elements.bar.style.width,'50%');assert(elements.speed.textContent.includes('12.5 МБ/с'));assert(!elements.pause.hidden)});
check('all tuning/model actions locked during pending/running transfer',()=>{for(const key of ['model','ctx','kvq4','threads','batchThreads','thinking','preset','pick','download','test','go','bench'])assert(elements[key].disabled,key)});
check('programmatic duplicate click cannot change settings or download',()=>{resetCalls();run('confirmDownload();startModel();preset();chooseLocal()');assert.equal(called.length,0)});
check('pause only requests pause',()=>{resetCalls();run("action('pause')");assert.deepEqual(called,['pause'])});
check('persisted partial offers resume',()=>{s.transfer={...s.transfer,state:'paused',busy:false,resumable:true};poll();assert.equal(elements.download.textContent,'Продолжить докачку');assert(elements.pause.hidden)});
check('resume consent preserves partial offsets',()=>{run('confirmDownload()');assert(lastConfirm.includes('сохранённых смещений'))});
check('import status and pause clearly labeled',()=>{s.transfer={...s.transfer,state:'import',busy:true};poll();assert(elements.status.textContent.includes('Импорт'));assert(elements.pause.textContent.includes('импорт'))});
check('verification not shown as network traffic',()=>{s.transfer.state='verify';poll();assert(elements.status.textContent.includes('SHA-256'));assert(elements.speed.textContent.includes('интернет не используется'))});
check('file completion does not autoload',()=>{resetCalls();s.transfer={...s.transfer,state:'ready',busy:false,resumable:false};s.hasModel=true;models[0].ready=true;s.engine.state=5;poll();assert.equal(called.length,0);assert(!elements.go.hidden&&!elements.go.disabled)});
check('explicit launch configures before native start',()=>{resetCalls();run('startModel()');assert.equal(called.at(-1),'start');assert.equal(called[0][0],'configure')});
check('model loading locks options and hides chat',()=>{s.engine.state=2;poll();assert(elements.model.disabled&&elements.pick.disabled&&elements.chat.hidden&&!elements.stop.hidden)});
check('ready runtime exposes chat and benchmark',()=>{s.engine.state=3;poll();assert(!elements.chat.hidden&&!elements.bench.disabled)});
check('benchmark opt-in runs real native facade action',()=>{resetCalls();run('startBenchmark()');assert.deepEqual(called,['benchmark']);assert(lastConfirm.includes('32'))});
check('benchmark busy locks repeat benchmark and hides chat',()=>{s.benchmark={...s.benchmark,state:'running',busy:true};poll();assert(elements.bench.disabled&&elements.chat.hidden)});
check('fixture timings rendered as engine values not elapsed-derived rates',()=>{s.benchmark={state:'done',busy:false,response:JSON.stringify({timings:{prompt_n:10,prompt_per_second:9.5,predicted_n:32,predicted_per_second:3.25}}),error:'',settings:s.options,elapsedMs:50000};poll();assert(elements.benchResult.textContent.includes('9.50'));assert(elements.benchResult.textContent.includes('3.25'));assert(elements.benchResult.textContent.includes('PTQ1_0'))});
check('missing timings not reported as speed success',()=>{s.benchmark.response='{}';poll();assert(elements.benchResult.textContent.includes('не вернул'))});
check('backend diagnostics inserted as text',()=>{run('showRuntime()');assert.equal(elements.runtime.textContent,'<runtime text>')});
check('runtime error remains literal text',()=>{s.engine.state=4;s.engine.error='<script>bad</script>';poll();assert.equal(elements.status.textContent,s.engine.error);assert(elements.chat.hidden)});
check('transfer error remains literal text',()=>{s.transfer.state='error';s.transfer.error='<img src=x onerror=bad>';poll();assert.equal(elements.status.textContent,s.transfer.error)});
check('legacy task never cancelled automatically',()=>{resetCalls();s.hasModel=false;s.engine.state=1;s.transfer={...s.transfer,state:'idle',busy:false,resumable:false};poll();assert.equal(called.length,0);assert.equal(elements.download.textContent,'Перейти на 8 соединений')});
check('legacy switch warns about old partial loss',()=>{run('confirmDownload()');assert(lastConfirm.includes('неполная часть не переносится'))});
check('runtime self-test success still reported',()=>{s.engine.state=0;s.engine.exit=0;poll();assert(elements.status.textContent.includes('код завершения 0'))});
console.log('JavaScript UI checks: '+n+' passed. DOM/bridge simulated, timings above are test fixtures.');
